### ISSUE TITLE
Name of the namespaces should not be prefixed of the enclosing namespaces

### ISSUE THREAD

**Issue by VincentBlondeau** [girba/jdt2famix#10]
E.g.:
"java.awt.image" namespace name  should be image and not java.awt

**Comment by girba** [comment]
I do not understand this issue. Could you provide more details? And possibly a way to reproduce?

**Comment by VincentBlondeau** [comment]
First parse the java file in the joined zip (it is one file of jdt2famix project): [issue.zip](https://github.com/girba/jdt2famix/files/476434/issue.zip)
it give a mse (in the zip) that you can import in Moose.

When importing, we expect to have 4 namespaces related to the model classes: (com, feenk, jdt2famix and injava), with feenk parentscope pointing to com, jdt2famix  parentscope pointing to feenk, .etc...

But here, we have only 1 namespace for the model com.feenk.jdt2famix.injava.

Same for stub namespaces for this mse, it should be created a package named java with 2 child scope namespaces io and lang.

That the first point.

Second, as the packages are nested, feenk namespace should not be named (attribute name) com.feenk but only feenk.

**Comment by girba** [comment]
Hmm. Something is strange because I fixed that, but it can be that it did not make it in a release. Could you try again with the latest version (not the release)?

**Comment by VincentBlondeau** [comment]
This is indeed fixed... I was on an oldest version....

**Comment by girba** [comment]
Great :). Do you confirm that it is in the 1.0.2 release?

**Comment by VincentBlondeau** [comment]
I confirm that is in the latest commit (c8d0e7e89375e8f63c062bdf6998fd4d94207510) and should be in the 1.02 release.

**Comment by girba** [comment]
Thanks :)
