### ISSUE TITLE
Some accesses are not in model

### ISSUE THREAD

**Issue by VincentBlondeau** [girba/jdt2famix#12]
I took as example the project https://github.com/awillemant/puho commit version 8c29333.

```
There is this code:
package puho.controller;
public class PublicHolidayControllerTests {
    private MockMvc mockMvc;
    @Autowired
    private WebApplicationContext webApplicationContext;
    @Before
    public void setup() throws Exception {
        this.mockMvc = webAppContextSetup(webApplicationContext).build();
    }
    ....
}
```

In the model, the method `PublicHolidayControllerTests::setup()` accesses contain only `webApplicationContext` and should also contain `mockMvc`.

**Comment by girba** [comment]
This is strange. I am taking a look.
